# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
a=[1,2,3,4]
arr=np.array(a)
arr

array([1, 2, 3, 4])

Lets create a matrix using list

In [3]:
from numpy import array
b=[[1,2,3],[11,22,33],[44,55,66]]
arr=np.array(b)
arr

array([[ 1,  2,  3],
       [11, 22, 33],
       [44, 55, 66]])

Now lets see how matlix looks like using numpy arrays

In [4]:
from numpy import array
b=[[1,2,3],[11,22,33],[44,55,66]]
arr=np.array(b)
arr

array([[ 1,  2,  3],
       [11, 22, 33],
       [44, 55, 66]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [5]:
np.zeros([10,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones([5,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
np.full([5,5],4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.linspace(1,11,10)

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [11]:
np.random.rand(5,5)

array([[0.25091848, 0.86368381, 0.58515635, 0.40445002, 0.26518339],
       [0.77456935, 0.3215624 , 0.15149165, 0.33637776, 0.96428702],
       [0.05655046, 0.85322353, 0.85679721, 0.31797616, 0.1247104 ],
       [0.1437426 , 0.51993156, 0.90917667, 0.31701632, 0.79631136],
       [0.55586068, 0.77707267, 0.37441051, 0.52979545, 0.2264296 ]])

In [16]:
arr=np.random.randint(0,10,(5,5))
arr

array([[6, 9, 2, 4, 6],
       [1, 0, 6, 8, 1],
       [9, 7, 7, 6, 2],
       [3, 7, 0, 7, 0],
       [0, 5, 0, 2, 5]], dtype=int32)

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution