##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [5]:

import numpy as np
arr=np.array([[1,2,3],[5,6,8]])
arr

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [15]:
arr=np.array([1,2,3])
print(arr[1])


2


Now lets see the 2D indexing aswell

In [20]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1,1])

5


In [21]:
print(arr[2,2])

9


In [23]:
print(arr[1,2])

6


Now we can also do the slicing lets see the **slicing in 1D**

In [24]:
arr=np.array([1,2,3,4,5,6,7])
arr[:3]


array([1, 2, 3])

1D slicing was really easy now lets see the **slicing in 2D**

In [35]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr[1:,1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[5, 6],
       [8, 9]])

There is one more thing known as **Boolean indexing**

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function