In [3]:
import numpy as np
import pandas as pd

In [4]:
x=([1,2,3],[20,21,22])
arr=np.array(x)
arr

array([[ 1,  2,  3],
       [20, 21, 22]])

In [7]:
y=([1,5,3],[27,20,22])
arr2=np.array(y)
arr2

array([[ 1,  5,  3],
       [27, 20, 22]])

In [8]:
arr*arr2

array([[  1,  10,   9],
       [540, 420, 484]])

In [9]:
arr+arr2 

array([[ 2,  7,  6],
       [47, 41, 44]])

In [ ]:
print("hello world this is dhruv panchal and i live in ahmedabad ")

hello world
