#Welcome numpy

In [1]:
import numpy as np

In [2]:
print("hii dhruv panchal")
print("how are you")

hii dhruv panchal
how are you


In [3]:
myarray=np.array([[2,22,45,65,1]])
myarray[0, 1]

np.int64(22)

In [4]:
myarray.shape

(1, 5)

In [5]:
myarray.dtype

dtype('int64')

In [6]:
myarray[0,1]=45 
myarray

array([[ 2, 45, 45, 65,  1]])

In [7]:
# ARRAY CREATION: CONVERSION FROM OTHER PYTHON STRUCTURES

In [8]:
listarray=np.array([[1,2,3] ,[7,8,9],[24,25,26]])
listarray

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [24, 25, 26]])

In [9]:
listarray.dtype

dtype('int64')

In [10]:
listarray.size

9

In [11]:
listarray.shape

(3, 3)

In [12]:
zeros=np.zeros((3,6))
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
rng= np.arange(0,10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
lspace=np.linspace(1,4,4)
lspace

array([1., 2., 3., 4.])

In [15]:
emp=np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.60219442e-306, 1.89146896e-307, 7.56571288e-307],
       [4.00544531e-307, 1.11261095e-306, 3.56043054e-307,
        1.37961641e-306, 2.22518251e-306, 1.33511969e-306],
       [6.23038336e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.86921143e-306, 6.23061763e-307],
       [6.23053954e-307, 1.33511018e-306, 8.45602762e-307,
        1.33511969e-306, 1.29061414e-306, 1.42410974e-306]])

In [16]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [17]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
x=[[1,2,3],[77,78,79],[41,42,43]]
arr=np.array(x)
arr

array([[ 1,  2,  3],
       [77, 78, 79],
       [41, 42, 43]])

In [ ]:
arr.sum(axis=0)

array([119, 122, 125])

In [ ]:
arr.sum(axis=1)

array([  6, 234, 126])

In [28]:
arr.argmax(axis=0)

array([1, 1, 1])

In [29]:
arr.argmax(axis=1)

array([2, 2, 2])

In [ ]:
arr.T

array([[ 1, 77, 41],
       [ 2, 78, 42],
       [ 3, 79, 43]])

In [23]:
arr.ndim

2

In [26]:
one=np.array([1,5,22,365,45,23])
one.argmax()


np.int64(3)

In [27]:
one.argmin()


np.int64(0)

In [30]:
arr

array([[ 1,  2,  3],
       [77, 78, 79],
       [41, 42, 43]])

In [34]:
y=[[1,4,6],[77,80,82],[43,44,47]]
arr2=np.array(y)
arr2

array([[ 1,  4,  6],
       [77, 80, 82],
       [43, 44, 47]])

In [37]:
arr

array([[ 1,  2,  3],
       [77, 78, 79],
       [41, 42, 43]])

In [38]:
arr + arr2

array([[  2,   6,   9],
       [154, 158, 161],
       [ 84,  86,  90]])

In [39]:
arr*arr2

array([[   1,    8,   18],
       [5929, 6240, 6478],
       [1763, 1848, 2021]])